import type { Strain } from "../types/strains";

export const STRAINS: Strain[] = [
  {
    id: "ak48",
    name: "AK48",
    thc: "11-13%",
    cbd: "9-10%",
    indica: 20,
    sativa: 80,
    description: "Seit Mitte der 90er Jahre sind AK-Varietäten immer beliebter geworden. Unsere AK-48 ist eine der stärksten, frühest blühenden Varietäten vorhanden. Die Pflanzen erzeugen harte Knospen mit einem außergewöhnlichen, penetranten Aroma. AK-48 ist zwar eine Hybride aus Indica und Sativa, doch bei seinem High-Effekt ähnelt er eher den Sativa. Obwohl die meisten Züchter sich für eine längere Wachstumsphase entscheiden würden, ist es unter perfekten Bedingungen möglich, AK-48 in nur 48 Tagen erntefähig zu machen.",
    effects: ["Tatkräftig", "Erhebend", "Energetisch"],
    medicalEffects: ["Gute Schlafförderung", "Möglicher Einsatz bei chronischen Schmerzen"],
    terpenes: ["Moschus", "Säuerlich", "Haschisch", "Floral"],
    genetics: "AK47 (Kolumbien x Mexiko x Thailand x Afghanistan) x ?",
    breeder: "Nirvana"
  },
  {
    id: "bizcocho",
    name: "Bizcocho",
    thc: "19-21%",
    cbd: "<2%",
    indica: 60,
    sativa: 40,
    description: "Der keksdominante Phänotyp von Bizcocho bietet ein außergewöhnlich komplexes und tiefes Geschmacksprofil, das besonders für Liebhaber von süßen, gasigen Sorten interessant ist. Die Effekte von Bizcocho ist langanhaltend und kombiniert mentale Klarheit mit körperlicher Entspannung, ideal für verschiedene Aktivitäten oder zur Entspannung.",
    effects: ["Mentale Klarheit", "Körperliche Entspannung"],
    terpenes: ["Süß", "Frisch gebackene Kekse", "Cookie-Gassigkeit", "Diesel", "Zkittlez"],
    genetics: "Biscotti x Bacio #4 × Zkittlez x (Road Dawg x Face Off OG Bx2)",
    breeder: "Grounded Genetics"
  },
  {
    id: "blue-gelato-41",
    name: "Blue Gelato 41",
    thc: "20-22%",
    cbd: "<2%",
    indica: 50,
    sativa: 50,
    description: "Blue Gelato 41 ist unsere sensationelle Blueberry Superkreuzung von der Westküste. Sie entstand durch das Kreuzen der berühmten Blueberry-Genetik mit Thin Mint Girl Scout Cookies und dem frisch-fruchtigem Indica Sunset Sherbet. Blue Gelato 41 reißt dich schnellstens in einen See tiefster psychedelischer Entspannung. Die Buds dieser Sorte sind harzig und versprühen ein süß-erdigen Zitronengeruch, wobei bei vielen Phänotypen die Färbung der Blüten blau bis lila wirkt.",
    effects: ["Sanfte Euphorie", "Stimmungsaufhellend", "Kreativ", "Körperliche Entspannung"],
    terpenes: ["Cremig-süß", "Fruchtig", "Erde", "Kush", "Vanillecreme", "Beeren"],
    genetics: "Sunset Sherbet × Thin Mint Girl Scout Cookies",
    breeder: "Seedstockers"
  },
  {
    id: "bubble-og",
    name: "Bubble OG",
    thc: "21-24%",
    cbd: "<2%",
    indica: 50,
    sativa: 50,
    description: "BUBBLE OG von LITFARMS ist eine Kreuzung aus Bubble Bath (The Soap x Project 4516) x LIT OG. Durch die Mischung aus den Mints-Soapy-Nuancen von The Soap und die Zkittlez-Noten aus Project 4516 kombiniert mit den OG lastigen Noten mit gas und pastry Tönen im Abgang ergibt sich hier doch eine ganz neue Mischung.",
    effects: ["Entspannend", "Beruhigend"],
    terpenes: ["Seifig", "Minze", "Lavendel", "Salbei", "Chemikalien", "Ammoniak", "OG-Noten", "Süßigkeiten"],
    genetics: "Bubble Bath (The Soap x Project 4516) x LIT OG",
    breeder: "LIT Farms Genetics"
  },
  {
    id: "double-rainbow-sherb",
    name: "Double Rainbow Sherb",
    thc: "20-24%",
    cbd: "<2%",
    indica: 50,
    sativa: 50,
    description: "RS-11 ist eine Indica-dominante Hybride, die durch Kreuzung von Pink Guava x OZK entstanden ist. Lemon Cherry Gelato bietet einen erstaunlichen Geschmack und eine Wirkung, die Sie in pure Glückseligkeit versetzen wird. Diese Knospe hat einen Geschmack, der genau dem entspricht, was ihr Name vermuten lässt – saure Zitronen gepaart mit reichhaltigen Kirschen und Beeren.",
    effects: ["Beruhigend", "Gemütlichkeit", "Glückseligkeit"],
    terpenes: ["Süß", "Fruchtig", "Kirsch-Beeren", "Zuckerbonbons", "Kiefer"],
    genetics: "RS11 x (RS11 x Lemon Cherry Gelato)",
    breeder: "LIT Farms Genetics"
  },
  {
    id: "gorilla-blueberry",
    name: "Gorilla x Blueberry",
    thc: "-",
    cbd: "-",
    indica: 50,
    sativa: 50,
    description: "Eine kraftvolle Kreuzung zwischen der legendären Gorilla Glue und der fruchtigen Blueberry.",
    effects: ["Ausgewogen"],
    terpenes: ["Beeren", "Erde", "Diesel"],
    genetics: "Gorilla Glue x Blueberry",
    breeder: "Unbekannt"
  },
  {
    id: "jelly-donutz",
    name: "Jelly Donutz",
    thc: "19-21%",
    cbd: "<2%",
    indica: 50,
    sativa: 50,
    description: "Die Wirkung ist zunächst klar, kreativ und aktivierend, bevor sie in eine angenehme körperliche Entspannung übergeht. Mit sehr hohen THC-Werten zählt Jelly Donutz zu den potenteren Sorten im CSCN-Portfolio, bleibt dabei aber angenehm ausbalanciert.",
    effects: ["Klar", "Kreativ", "Aktivierend", "Körperliche Entspannung"],
    terpenes: ["Süß", "Gummibärchen", "Gasig", "Tropisch", "Sahnig", "Gebratener Donut"],
    genetics: "Jelly Donutz (#160x#17) x Hella Jelly x White Runtz",
    breeder: "Humboldt Seed Company (Twentyk Cut)"
  },
  {
    id: "platinum-kush",
    name: "Platinum Kush",
    thc: "22%",
    cbd: "<2%",
    indica: 80,
    sativa: 20,
    description: "Platinum Kush Breath von In-House ist Platinum x OGKB V2.1. Sie sieht fantastisch aus, duftet nach einem gedämpften Haschisch-Gas-Aroma und wirkt erdend. Platinum ist angeblich eine Old-School-Kreuzung aus UW Hashplant und Permafrost.",
    effects: ["Beruhigend", "Körperbetonte Wirkung"],
    terpenes: ["Erdig", "Würzig", "Kush", "Hash-lastig"],
    genetics: "Platinum x OGKB",
    breeder: "In House Genetics"
  },
  {
    id: "pnw-cherries",
    name: "PNW Cherries",
    thc: "20-22%",
    cbd: "0-8%",
    indica: 50,
    sativa: 50,
    description: "PNW Cherries erzeugt eine ausgewogene, eher klare, Kopflastige Wirkung. Sie beginnt mit einem zerebralen High, das kreativitätsfördernd und stimmungsaufhellend wirkt. Im weiteren Verlauf kann ein angenehmes Körpergefühl einsetzen.",
    effects: ["Zerebral", "Kreativ", "Stimmungsaufhellend", "Körpergefühl"],
    terpenes: ["Süßlich", "Erdig", "Kirschduft"],
    genetics: "PNW Dogshit × Black Cherry Honey",
    breeder: "Inhouse Genetics"
  },
  {
    id: "sugar-cane",
    name: "Sugar Cane",
    thc: "20%",
    cbd: "<2%",
    indica: 50,
    sativa: 50,
    description: "Die Wirkung setzt mit einem erhebenden zerebralen High ein, das den Geist klärt und die Kreativität anregt. Während das High fortschreitet, tritt eine wohltuende körperliche Entspannung ein, die jedoch nicht dazu führt an die Couch gebunden zu sein.",
    effects: ["Erhebend", "Geist klärend", "Kreativität", "Körperliche Entspannung"],
    terpenes: ["Süß", "Karamellisierter Zucker", "Sirup", "Trauben", "Blumig", "Zuckerwatte"],
    genetics: "Platinum x Slurricane",
    breeder: "Inhouse Genetics"
  }
];
