import type { Strain } from "../types/strains";

export const STRAINS: Strain[] = [
  {
    id: "ak48",
    name: "AK48",
    thc: "11-13%",
    cbd: "9-10%",
    indica: 20,
    sativa: 80,
    description: "Seit Mitte der 90er Jahre sind AK-Varietäten immer beliebter geworden. Unsere AK-48 ist eine der stärksten, frühest blühenden Varietäten vorhanden. Die Pflanzen erzeugen harte Knospen mit einem außergewöhnlichen, penetranten Aroma. AK-48 ist zwar eine Hybride aus Indica und Sativa, doch bei seinem High-Effekt ähnelt er eher den Sativa. Obwohl die meisten Züchter sich für eine längere Wachstumsphase entscheiden würden, ist es unter perfekten Bedingungen möglich, AK-48 in nur 48 Tagen erntefähig zu machen.",
    description_en: "Since the mid-90s, AK varieties have become increasingly popular. Our AK-48 is one of the strongest, earliest flowering varieties available. The plants produce hard buds with an exceptional, pungent aroma. Although AK-48 is a hybrid of Indica and Sativa, its high effect is more similar to Sativa. While most growers would opt for a longer growth phase, under perfect conditions it is possible to make AK-48 ready for harvest in just 48 days.",
    effects: ["Tatkräftig", "Erhebend", "Energetisch"],
    effects_en: ["Energetic", "Uplifting", "Active"],
    medicalEffects: ["Gute Schlafförderung", "Möglicher Einsatz bei chronischen Schmerzen"],
    medicalEffects_en: ["Good sleep support", "Possible use for chronic pain"],
    terpenes: ["Moschus", "Säuerlich", "Haschisch", "Floral"],
    terpenes_en: ["Musk", "Sour", "Hashish", "Floral"],
    genetics: "AK47 (Kolumbien x Mexiko x Thailand x Afghanistan) x ?",
    breeder: "Nirvana"
  },
  {
    id: "bizcocho",
    name: "Bizcocho",
    thc: "19-21%",
    cbd: "<2%",
    indica: 60,
    sativa: 40,
    description: "Der keksdominante Phänotyp von Bizcocho bietet ein außergewöhnlich komplexes und tiefes Geschmacksprofil, das besonders für Liebhaber von süßen, gasigen Sorten interessant ist. Die Effekte von Bizcocho ist langanhaltend und kombiniert mentale Klarheit mit körperlicher Entspannung, ideal für verschiedene Aktivitäten oder zur Entspannung.",
    description_en: "The cookie-dominant phenotype of Bizcocho offers an exceptionally complex and deep flavor profile, particularly interesting for lovers of sweet, gassy strains. The effects of Bizcocho are long-lasting and combine mental clarity with physical relaxation, ideal for various activities or unwinding.",
    effects: ["Mentale Klarheit", "Körperliche Entspannung"],
    effects_en: ["Mental Clarity", "Physical Relaxation"],
    terpenes: ["Süß", "Frisch gebackene Kekse", "Cookie-Gassigkeit", "Diesel", "Zkittlez"],
    terpenes_en: ["Sweet", "Freshly baked cookies", "Cookie gassiness", "Diesel", "Zkittlez"],
    genetics: "Biscotti x Bacio #4 × Zkittlez x (Road Dawg x Face Off OG Bx2)",
    breeder: "Grounded Genetics"
  },
  {
    id: "blue-gelato-41",
    name: "Blue Gelato 41",
    thc: "20-22%",
    cbd: "<2%",
    indica: 50,
    sativa: 50,
    description: "Blue Gelato 41 ist unsere sensationelle Blueberry Superkreuzung von der Westküste. Sie entstand durch das Kreuzen der berühmten Blueberry-Genetik mit Thin Mint Girl Scout Cookies und dem frisch-fruchtigem Indica Sunset Sherbet. Blue Gelato 41 reißt dich schnellstens in einen See tiefster psychedelischer Entspannung. Die Buds dieser Sorte sind harzig und versprühen ein süß-erdigen Zitronengeruch, wobei bei vielen Phänotypen die Färbung der Blüten blau bis lila wirkt.",
    description_en: "Blue Gelato 41 is our sensational Blueberry supercross from the West Coast. It was created by crossing the famous Blueberry genetics with Thin Mint Girl Scout Cookies and the fresh-fruity Indica Sunset Sherbet. Blue Gelato 41 quickly pulls you into a sea of deep psychedelic relaxation. The buds of this strain are resinous and exude a sweet-earthy lemon scent, with many phenotypes appearing blue to purple in color.",
    effects: ["Sanfte Euphorie", "Stimmungsaufhellend", "Kreativ", "Körperliche Entspannung"],
    effects_en: ["Gentle Euphoria", "Mood-enhancing", "Creative", "Physical Relaxation"],
    terpenes: ["Cremig-süß", "Fruchtig", "Erde", "Kush", "Vanillecreme", "Beeren"],
    terpenes_en: ["Creamy-sweet", "Fruity", "Earthy", "Kush", "Vanilla Cream", "Berries"],
    genetics: "Sunset Sherbet × Thin Mint Girl Scout Cookies",
    breeder: "Seedstockers"
  },
  {
    id: "bubble-og",
    name: "Bubble OG",
    thc: "21-24%",
    cbd: "<2%",
    indica: 50,
    sativa: 50,
    description: "BUBBLE OG von LITFARMS ist eine Kreuzung aus Bubble Bath (The Soap x Project 4516) x LIT OG. Durch die Mischung aus den Mints-Soapy-Nuancen von The Soap und die Zkittlez-Noten aus Project 4516 kombiniert mit den OG lastigen Noten mit gas und pastry Tönen im Abgang ergibt sich hier doch eine ganz neue Mischung.",
    description_en: "BUBBLE OG by LITFARMS is a cross between Bubble Bath (The Soap x Project 4516) x LIT OG. By mixing the minty-soapy nuances of The Soap and the Zkittlez notes from Project 4516 combined with OG-heavy notes containing gas and pastry tones on the finish, a completely new blend emerges.",
    effects: ["Entspannend", "Beruhigend"],
    effects_en: ["Relaxing", "Calming"],
    terpenes: ["Seifig", "Minze", "Lavendel", "Salbei", "Chemikalien", "Ammoniak", "OG-Noten", "Süßigkeiten"],
    terpenes_en: ["Soapy", "Mint", "Lavender", "Sage", "Chemicals", "Ammonia", "OG notes", "Sweets"],
    genetics: "Bubble Bath (The Soap x Project 4516) x LIT OG",
    breeder: "LIT Farms Genetics"
  },
  {
    id: "double-rainbow-sherb",
    name: "Double Rainbow Sherb",
    thc: "20-24%",
    cbd: "<2%",
    indica: 50,
    sativa: 50,
    description: "RS-11 ist eine Indica-dominante Hybride, die durch Kreuzung von Pink Guava x OZK entstanden ist. Lemon Cherry Gelato bietet einen erstaunlichen Geschmack und eine Wirkung, die Sie in pure Glückseligkeit versetzen wird. Diese Knospe hat einen Geschmack, der genau dem entspricht, was ihr Name vermuten lässt – saure Zitronen gepaart mit reichhaltigen Kirschen und Beeren.",
    description_en: "RS-11 is an Indica-dominant hybrid created by crossing Pink Guava x OZK. Lemon Cherry Gelato offers an amazing taste and an effect that will put you in pure bliss. This bud has a flavor that matches exactly what its name suggests – sour lemons paired with rich cherries and berries.",
    effects: ["Beruhigend", "Gemütlichkeit", "Glückseligkeit"],
    effects_en: ["Calming", "Comfort", "Bliss"],
    terpenes: ["Süß", "Fruchtig", "Kirsch-Beeren", "Zuckerbonbons", "Kiefer"],
    terpenes_en: ["Sweet", "Fruity", "Cherry-Berry", "Sugar Candy", "Pine"],
    genetics: "RS11 x (RS11 x Lemon Cherry Gelato)",
    breeder: "LIT Farms Genetics"
  },
  {
    id: "gorilla-blueberry",
    name: "Gorilla x Blueberry",
    thc: "-",
    cbd: "-",
    indica: 50,
    sativa: 50,
    description: "Eine kraftvolle Kreuzung zwischen der legendären Gorilla Glue und der fruchtigen Blueberry.",
    description_en: "A powerful cross between the legendary Gorilla Glue and the fruity Blueberry.",
    effects: ["Ausgewogen"],
    effects_en: ["Balanced"],
    terpenes: ["Beeren", "Erde", "Diesel"],
    terpenes_en: ["Berries", "Earth", "Diesel"],
    genetics: "Gorilla Glue x Blueberry",
    breeder: "Unbekannt"
  },
  {
    id: "jelly-donutz",
    name: "Jelly Donutz",
    thc: "19-21%",
    cbd: "<2%",
    indica: 50,
    sativa: 50,
    description: "Die Wirkung ist zunächst klar, kreativ und aktivierend, bevor sie in eine angenehme körperliche Entspannung übergeht. Mit sehr hohen THC-Werten zählt Jelly Donutz zu den potenteren Sorten im CSCN-Portfolio, bleibt dabei aber angenehm ausbalanciert.",
    description_en: "The effect is initially clear, creative, and activating before transitioning into a pleasant physical relaxation. With very high THC levels, Jelly Donutz is one of the more potent strains in the CSCN portfolio, while remaining pleasantly balanced.",
    effects: ["Klar", "Kreativ", "Aktivierend", "Körperliche Entspannung"],
    effects_en: ["Clear", "Creative", "Activating", "Physical Relaxation"],
    terpenes: ["Süß", "Gummibärchen", "Gasig", "Tropisch", "Sahnig", "Gebratener Donut"],
    terpenes_en: ["Sweet", "Gummy bears", "Gassy", "Tropical", "Creamy", "Fried Donut"],
    genetics: "Jelly Donutz (#160x#17) x Hella Jelly x White Runtz",
    breeder: "Humboldt Seed Company (Twentyk Cut)",
    isSoldOut: true
  },
  {
    id: "platinum-kush",
    name: "Platinum Kush",
    thc: "22%",
    cbd: "<2%",
    indica: 80,
    sativa: 20,
    description: "Platinum Kush Breath von In-House ist Platinum x OGKB V2.1. Sie sieht fantastisch aus, duftet nach einem gedämpften Haschisch-Gas-Aroma und wirkt erdend. Platinum ist angeblich eine Old-School-Kreuzung aus UW Hashplant und Permafrost.",
    description_en: "Platinum Kush Breath from In-House is Platinum x OGKB V2.1. It looks fantastic, smells like a muted hash-gas aroma, and has a grounding effect. Platinum is reportedly an old-school cross of UW Hashplant and Permafrost.",
    effects: ["Beruhigend", "Körperbetonte Wirkung"],
    effects_en: ["Calming", "Body-focused effect"],
    terpenes: ["Erdig", "Würzig", "Kush", "Hash-lastig"],
    terpenes_en: ["Earthy", "Spicy", "Kush", "Hashy"],
    genetics: "Platinum x OGKB",
    breeder: "In House Genetics"
  },
  {
    id: "pnw-cherries",
    name: "PNW Cherries",
    thc: "20-22%",
    cbd: "0-8%",
    indica: 50,
    sativa: 50,
    description: "PNW Cherries erzeugt eine ausgewogene, eher klare, Kopflastige Wirkung. Sie beginnt mit einem zerebralen High, das kreativitätsfördernd und stimmungsaufhellend wirkt. Im weiteren Verlauf kann ein angenehmes Körpergefühl einsetzen.",
    description_en: "PNW Cherries produces a balanced, rather clear, head-heavy effect. It starts with a cerebral high that is creativity-enhancing and mood-boosting. In the further course, a pleasant body feeling can set in.",
    effects: ["Zerebral", "Kreativ", "Stimmungsaufhellend", "Körpergefühl"],
    effects_en: ["Cerebral", "Creative", "Mood-enhancing", "Body sensation"],
    terpenes: ["Süßlich", "Erdig", "Kirschduft"],
    terpenes_en: ["Sweetish", "Earthy", "Cherry scent"],
    genetics: "PNW Dogshit × Black Cherry Honey",
    breeder: "Inhouse Genetics"
  },
  {
    id: "sugar-cane",
    name: "Sugar Cane",
    thc: "20%",
    cbd: "<2%",
    indica: 50,
    sativa: 50,
    description: "Die Wirkung setzt mit einem erhebenden zerebralen High ein, das den Geist klärt und die Kreativität anregt. Während das High fortschreitet, tritt eine wohltuende körperliche Entspannung ein, die jedoch nicht dazu führt an die Couch gebunden zu sein.",
    description_en: "The effect sets in with an uplifting cerebral high that clears the mind and stimulates creativity. As the high progresses, a soothing physical relaxation occurs that does not lead to being couch-locked.",
    effects: ["Erhebend", "Geist klärend", "Kreativität", "Körperliche Entspannung"],
    effects_en: ["Uplifting", "Mind-clearing", "Creativity", "Physical Relaxation"],
    terpenes: ["Süß", "Karamellisierter Zucker", "Sirup", "Trauben", "Blumig", "Zuckerwatte"],
    terpenes_en: ["Sweet", "Caramelized sugar", "Syrup", "Grapes", "Floral", "Cotton candy"],
    genetics: "Platinum x Slurricane",
    breeder: "Inhouse Genetics"
  }
];
